CREATE TABLE Tasks
(
Id_task INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
Id_todo INT(11) NOT NULL,
Content VARCHAR(30) NOT NULL,
Done TINYINT(1) DEFAULT '0',
CONSTRAINT Tasks_Todos_Id_todo_fk FOREIGN KEY (Id_todo) REFERENCES Todos (Id_todo) ON DELETE CASCADE
);
CREATE INDEX Tasks_Todos_Id_todo_fk ON Tasks (Id_todo);
CREATE TABLE Todos
(
Id_todo INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
Author INT(11) NOT NULL,
Title VARCHAR(50) NOT NULL,
Add_date DATETIME NOT NULL,
Cat_id INT(11) NOT NULL,
Display_order INT(11) DEFAULT '1',
CONSTRAINT Todos_Users_Id_User_fk FOREIGN KEY (Author) REFERENCES Users (Id_User) ON DELETE CASCADE
);
CREATE INDEX Todos_Users_Id_User_fk ON Todos (Author);
CREATE TABLE Users
(
Id_User INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
Login VARCHAR(32) NOT NULL,
Password VARCHAR(128) NOT NULL,
First_Name VARCHAR(32) NOT NULL,
Last_Name VARCHAR(32) NOT NULL
);
CREATE UNIQUE INDEX Users_Id_User_uindex ON Users (Id_User);
CREATE UNIQUE INDEX Users_Login_uindex ON Users (Login);